version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile
      context: ./pkg/client/postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "hackathon"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MINIO_HOST: "minio"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "FUszpbQU8qSx1lNEM2Yw"
      MINIO_SECRET_KEY: "gOeqwnGKwzcsnx19h0RogHp8zxfncqjP44zwDHIQ"
      MINIO_BUCKET_NAME: "betera"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "hackathon"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      ENVIRONMENT: "dev" # dev, prod
    depends_on:
      - minio
      - postgres
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - server

networks:
  app-network:
    driver: bridge

volumes:
  data:
  minio-storage: