POST localhost:8000/task/create
Content-Type: application/json

{
  "task_id": 0,
  "title": "Task",
  "description": "SomeDesc.",
  "difficulty": 1,
  "priority": "mid",
  "status": "in progress",
  "start": "2006-01-02T15:04:05Z",
  "end": "2006-02-02T15:04:05Z"
}

###

POST localhost:8000/task/done/1
Content-Type: application/json

###

POST localhost:8000/task/delete/2
Content-Type: application/json
